### ISSUE TITLE
UnicodeDecodeError exception in _get_filename_relative_to_find_dir

### ISSUE THREAD

**Issue by sunxd-chromium** [natduca/quickopen#52]
The newly added file [file-for-drag-to-send3-ABC~‾¥≈¤･・•∙·☼★星🌟星★☼·∙•・･¤≈¥‾~XYZ.txt](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/http/tests/local/fileapi/resources/file-for-drag-to-send3-ABC~%E2%80%BE%C2%A5%E2%89%88%C2%A4%EF%BD%A5%E3%83%BB%E2%80%A2%E2%88%99%C2%B7%E2%98%BC%E2%98%85%E6%98%9F%F0%9F%8C%9F%E6%98%9F%E2%98%85%E2%98%BC%C2%B7%E2%88%99%E2%80%A2%E3%83%BB%EF%BD%A5%C2%A4%E2%89%88%C2%A5%E2%80%BE~XYZ.txt?type=cs&q=file-for-drag-to-send3-&sq=package:chromium&l=1) in chromium code base could raise the exception in the issue title. I think files with a name that could cause such an exception should be ignored.

**Comment by mattto** [comment]
Yes my quickopend seems to be crashing today with a UnicodeDecodeError.  But strangely it should already been ignoring LayoutTests and deleting those file-for-drag files didn't seem to fix it.

```
Traceback (most recent call last):
  File "./quickopend", line 18, in <module>
    sys.exit(bootstrap.main('src.quickopend'))
  File "/work/quickopen/src/bootstrap.py", line 178, in main
    sys.exit(run())
  File "/work/quickopen/src/bootstrap.py", line 78, in run
    return mod.main(parser)
  File "/work/quickopen/src/quickopend.py", line 256, in main
    return CMDrun(parser)
  File "/work/quickopen/src/quickopend.py", line 83, in CMDrun
    service.run()
  File "/work/quickopen/src/daemon.py", line 214, in run
    self.serve_forever()
  File "/work/quickopen/src/daemon.py", line 194, in serve_forever
    item.cb(*item.args)
  File "/work/quickopen/src/db_stub.py", line 54, in _index_a_bit_more
    self.db.step_indexer()
  File "/work/quickopen/src/../third_party/py_trace_event/trace_event_impl/decorators.py", line 50, in traced_function
    return func(*args, **kwargs)
  File "/work/quickopen/src/db.py", line 209, in step_indexer
    self._cur_shard_manager = DBShardManager(self._pending_indexer)
  File "/work/quickopen/src/db_shard_manager.py", line 64, in __init__
    shard.apply(ShardInit, (chunk,))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 244, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 941444: ordinal not in range(128)
```
